# Generated by Django 5.1.6 on 2026-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0003_phase4_move_grade"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section', 'status'], name='idx_enrollment_section_status'),
        ),
    ]
