# Generated by Django 5.1.15 on 2026-05-13 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_phase6_perf_indexes'),
        ('instructors', '0003_add_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='instructor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='instructor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='instructor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to='instructors.instructorprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='instructor_comment',
            field=models.TextField(blank=True, help_text='Eğitim görevlisinin notu'),
        ),
    ]
