# Generated by Django 5.1.15 on 2026-05-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_electivepool_created_at'),
        ('enrollments', '0005_enrollment_instructor_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='reassignment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reassignment_suggested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_suggestions', to='courses.course'),
        ),
    ]
