# Generated by Django 5.1.15 on 2026-05-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_add_reassignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed'), ('waitlisted', 'Bekleme listesi')], db_index=True, default='enrolled', max_length=20),
        ),
    ]
