# Generated by Django 5.1.15 on 2026-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_backfill_student_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Yönetici onayı verildi mi? Onaysız öğrenciler kayıt işlemi yapamaz.'),
        ),
    ]
