# Generated by Django 5.1.6 on 2026-03-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='students.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uniq_program_department_name'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'target_role'], name='idx_ann_active_role'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['student', 'semester'], name='idx_transcript_student_sem'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='uniq_transcript_student_semester'),
        ),
    ]
