# Generated by Django 5.1.6 on 2026-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_phase4_grade"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sectiontimeslot",
            index=models.Index(fields=["section", "weekday"], name="idx_timeslot_section_weekday"),
        ),
    ]
