# Generated by Django 5.1.15 on 2026-05-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_curriculum_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='credits_required',
            field=models.PositiveSmallIntegerField(default=240, help_text='Mezuniyet için gereken toplam AKTS kredisi.'),
        ),
    ]
