# Generated by Django 5.1.6 on 2026-03-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('building', models.CharField(db_index=True, max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('building', 'room_number'),
                'constraints': [models.UniqueConstraint(fields=('building', 'room_number'), name='uniq_classroom_building_room')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academic.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.program')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('section', models.CharField(max_length=10)),
                ('quota', models.PositiveIntegerField(default=30)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='courses.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='instructors.instructorprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academic.semester')),
            ],
            options={
                'ordering': ('-semester__academic_year', 'course__code', 'section'),
                'indexes': [models.Index(fields=['semester', 'is_active'], name='idx_offering_sem_active'), models.Index(fields=['instructor'], name='idx_offering_instructor')],
                'constraints': [models.UniqueConstraint(fields=('course', 'semester', 'section'), name='uniq_offering_course_semester_section')],
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='courses.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_links', to='courses.course')),
            ],
            options={
                'ordering': ('course__code',),
                'constraints': [models.UniqueConstraint(fields=('course', 'prerequisite'), name='uniq_course_prerequisite'), models.CheckConstraint(condition=models.Q(('course', models.F('prerequisite')), _negated=True), name='check_course_not_self_prereq')],
            },
        ),
    ]
