# Generated by Django 5.1.15 on 2026-05-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_elective_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivepool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
