# Generated by Django 5.1.15 on 2026-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_add_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='is_advisor',
            field=models.BooleanField(default=False, help_text='Danışman yetkisi var mı? Sadece danışmanlar öğrenci ders onayı yapabilir.'),
        ),
    ]
